using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Jellyfin.Plugin.Sentinel.Diagnostics;
using Jellyfin.Plugin.Sentinel.Domain;
using Jellyfin.Plugin.Sentinel.Persistence;
using MediaBrowser.Controller.Library;
using MediaBrowser.Controller.Session;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.Sentinel.Collector;

/// <summary>
/// Observes finished playback sessions and turns them into persisted diagnoses.
/// Registered as an <see cref="IHostedService"/> — the main <see cref="Plugin"/> class
/// cannot be one itself, per Jellyfin's plugin constraints.
/// </summary>
/// <remarks>
/// <para>
/// Also subscribes to <c>PlaybackProgress</c>, not just <c>PlaybackStopped</c>. This is required,
/// not optional: verified against <c>Emby.Server.Implementations.Session.SessionManager</c>
/// source, Jellyfin's own <c>OnPlaybackStopped</c> always calls <c>RemoveNowPlayingItem(session)</c>
/// — which resets <c>session.PlayState</c> to a brand-new, empty object and clears
/// <c>session.TranscodingInfo</c> to null — before firing <c>PlaybackStopped</c>. A handler that
/// only listens to <c>PlaybackStopped</c> and reads <c>Session.PlayState</c>/<c>TranscodingInfo</c>
/// will therefore always see empty values, for every session, regardless of whether it actually
/// transcoded. The last known state must be captured earlier, during <c>PlaybackProgress</c>
/// (where it is still live), cached per play session, and consumed when the session stops.
/// </para>
/// <para>
/// The two events are not dispatched the same way — verified against the same source.
/// <c>SessionManager.OnPlaybackProgress</c> invokes its subscribers inline, on whatever thread
/// called it (an incoming client HTTP request, or the session's own once-a-second automatic
/// progress timer). <c>SessionManager.OnPlaybackStopped</c> instead queues its subscribers onto
/// the thread pool via <c>EventHelper.QueueEventIfNotNull</c> and dispatches them asynchronously.
/// Because of that asymmetry, a progress tick already in flight (including one generated by the
/// automatic timer replaying the client's last known state) can still land *after* Jellyfin has
/// cleared <c>TranscodingInfo</c> — or even reset <c>PlayState</c> entirely — for a session that
/// is about to stop, but *before* the queued stop handler below consumes the cached snapshot,
/// overwriting good data with empty data. The cache write in <see cref="OnPlaybackProgress"/>
/// below merges rather than replaces for exactly this reason, for every field including
/// <c>PlayMethod</c>: once real data has been observed for a play session, a later, emptier tick
/// for the same play session never erases it.
/// </para>
/// <para>
/// One more verified Jellyfin quirk this handles: <c>SessionManager.CheckForIdlePlayback</c> —
/// the timer that stops a session Jellyfin never heard from again (a crashed client, a dropped
/// connection) — builds its own <c>PlaybackStopInfo</c> without setting <c>PlaySessionId</c> at
/// all, so <c>PlaybackStopEventArgs.PlaySessionId</c> is null for every idle-timeout stop.
/// Relying on <c>PlaySessionId</c> alone would silently produce zero diagnoses for exactly the
/// sessions most likely to be worth diagnosing — a playback that never sent a normal stop report.
/// The secondary <c>Session.Id</c>-to-<c>PlaySessionId</c> index below exists for this one case:
/// it lets a stop event with no <c>PlaySessionId</c> fall back to the most recent play session
/// observed for that device-scoped <c>Session.Id</c>.
/// </para>
/// </remarks>
public sealed partial class PlaybackCollectorHostedService : IHostedService
{
    private static readonly TimeSpan SnapshotTtl = TimeSpan.FromMinutes(30);

    private readonly ISessionManager _sessionManager;
    private readonly RuleEngine _ruleEngine;
    private readonly PlaybackEventRepository _playbackEventRepository;
    private readonly DiagnosisRepository _diagnosisRepository;
    private readonly IncidentRepository _incidentRepository;
    private readonly TimeProvider _timeProvider;
    private readonly ILogger<PlaybackCollectorHostedService> _logger;
    private readonly ConcurrentDictionary<string, PlaybackProgressSnapshot> _lastKnownPlaybackState = new();

    // Not subject to the same unbounded-growth concern as the dictionary above: it's keyed by
    // the device-scoped Session.Id, whose keyspace is bounded by the number of distinct
    // app+device+user combinations this server has ever seen (see remarks), and each entry is
    // simply overwritten by that device's next playback — it never accumulates one entry per
    // playback the way a PlaySessionId-keyed cache would.
    private readonly ConcurrentDictionary<string, string> _lastKnownPlaySessionIdBySessionId = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="PlaybackCollectorHostedService"/> class.
    /// </summary>
    /// <param name="sessionManager">The Jellyfin session manager to observe playback events from.</param>
    /// <param name="ruleEngine">The rule engine used to diagnose playback events.</param>
    /// <param name="playbackEventRepository">The repository used to persist playback events.</param>
    /// <param name="diagnosisRepository">The repository used to persist diagnoses.</param>
    /// <param name="incidentRepository">The repository used to track incidents derived from diagnoses.</param>
    /// <param name="timeProvider">The time provider used for the snapshot-cache TTL sweep.</param>
    /// <param name="logger">The logger.</param>
    /// <exception cref="ArgumentNullException">Thrown when any parameter is null.</exception>
    public PlaybackCollectorHostedService(
        ISessionManager sessionManager,
        RuleEngine ruleEngine,
        PlaybackEventRepository playbackEventRepository,
        DiagnosisRepository diagnosisRepository,
        IncidentRepository incidentRepository,
        TimeProvider timeProvider,
        ILogger<PlaybackCollectorHostedService> logger)
    {
        ArgumentNullException.ThrowIfNull(sessionManager);
        ArgumentNullException.ThrowIfNull(ruleEngine);
        ArgumentNullException.ThrowIfNull(playbackEventRepository);
        ArgumentNullException.ThrowIfNull(diagnosisRepository);
        ArgumentNullException.ThrowIfNull(incidentRepository);
        ArgumentNullException.ThrowIfNull(timeProvider);
        ArgumentNullException.ThrowIfNull(logger);

        _sessionManager = sessionManager;
        _ruleEngine = ruleEngine;
        _playbackEventRepository = playbackEventRepository;
        _diagnosisRepository = diagnosisRepository;
        _incidentRepository = incidentRepository;
        _timeProvider = timeProvider;
        _logger = logger;
    }

    /// <inheritdoc />
    public Task StartAsync(CancellationToken cancellationToken)
    {
        _sessionManager.PlaybackProgress += OnPlaybackProgress;
        _sessionManager.PlaybackStopped += OnPlaybackStopped;
        LogCollectorStarted(_logger);
        return Task.CompletedTask;
    }

    /// <inheritdoc />
    public Task StopAsync(CancellationToken cancellationToken)
    {
        _sessionManager.PlaybackProgress -= OnPlaybackProgress;
        _sessionManager.PlaybackStopped -= OnPlaybackStopped;

        // Don't hold cached playback state across a stop/start cycle of this service.
        _lastKnownPlaybackState.Clear();
        _lastKnownPlaySessionIdBySessionId.Clear();
        return Task.CompletedTask;
    }

    private void OnPlaybackProgress(object? sender, PlaybackProgressEventArgs args)
    {
        // This one genuinely does run inline on Jellyfin's own call path (see class remarks) —
        // an uncaught exception here would propagate into SessionManager.OnPlaybackProgress
        // itself, not just into this plugin. Never let anything escape this handler.
        try
        {
            var playSessionId = args.PlaySessionId;
            if (string.IsNullOrEmpty(playSessionId))
            {
                return;
            }

            var session = args.Session;
            var sessionId = session?.Id;
            if (!string.IsNullOrEmpty(sessionId))
            {
                _lastKnownPlaySessionIdBySessionId[sessionId] = playSessionId;
            }

            var transcodingInfo = session?.TranscodingInfo;
            var observedPlayMethod = session?.PlayState?.PlayMethod;
            var observedReasons = transcodingInfo?.TranscodeReasons;
            var now = _timeProvider.GetTimestamp();

            _lastKnownPlaybackState.AddOrUpdate(
                playSessionId,
                _ => new PlaybackProgressSnapshot
                {
                    PlayMethod = observedPlayMethod,
                    TranscodeReasons = observedReasons ?? default,
                    VideoCodec = transcodingInfo?.VideoCodec,
                    AudioCodec = transcodingInfo?.AudioCodec,
                    CapturedAtTimestamp = now
                },
                (_, previous) => new PlaybackProgressSnapshot
                {
                    PlayMethod = observedPlayMethod ?? previous.PlayMethod,
                    TranscodeReasons = observedReasons is { } reasons && reasons != default
                        ? reasons
                        : previous.TranscodeReasons,
                    VideoCodec = transcodingInfo?.VideoCodec ?? previous.VideoCodec,
                    AudioCodec = transcodingInfo?.AudioCodec ?? previous.AudioCodec,
                    CapturedAtTimestamp = now
                });

            EvictStaleSnapshots(now);
        }
#pragma warning disable CA1031
        catch (Exception ex)
        {
            LogPlaybackProgressHandlerFailed(_logger, ex);
        }
#pragma warning restore CA1031
    }

    private void OnPlaybackStopped(object? sender, PlaybackStopEventArgs args)
    {
        // Unlike OnPlaybackProgress above, Jellyfin dispatches PlaybackStopped asynchronously
        // via EventHelper.QueueEventIfNotNull (its own Task.Run with its own try/catch), so an
        // exception here would not break Jellyfin's own stop handling (which has already run by
        // the time this fires) — but it would still be swallowed by Jellyfin's generic catch
        // instead of logged with this plugin's own session/diagnosis context. Never let anything
        // escape this handler.
        try
        {
            var playSessionId = args.PlaySessionId;
            var sessionId = args.Session?.Id;

            // CheckForIdlePlayback stops never carry a PlaySessionId (see class remarks) — fall
            // back to the most recent one seen for this device-scoped Session.Id.
            if (string.IsNullOrEmpty(playSessionId) && !string.IsNullOrEmpty(sessionId))
            {
                _lastKnownPlaySessionIdBySessionId.TryGetValue(sessionId, out playSessionId);
            }

            PlaybackProgressSnapshot? snapshot = null;
            if (!string.IsNullOrEmpty(playSessionId))
            {
                // Removed, not just read: this play session is ending, and leaving it behind
                // would let a stale entry outlive its usefulness.
                _lastKnownPlaybackState.TryRemove(playSessionId, out snapshot);

                if (!string.IsNullOrEmpty(sessionId))
                {
                    // Conditional removal: only clear the secondary index if it still points at
                    // the play session that just ended, so it never accidentally deletes a
                    // pointer a subsequent PlaybackProgress tick already advanced past this one.
                    ((ICollection<KeyValuePair<string, string>>)_lastKnownPlaySessionIdBySessionId)
                        .Remove(new KeyValuePair<string, string>(sessionId, playSessionId));
                }
            }

            var playbackEvent = PlaybackEventFactory.FromEventArgs(args, snapshot);
            if (playbackEvent is null)
            {
                return;
            }

            var playbackEventId = _playbackEventRepository.Insert(playbackEvent);
            var diagnoses = _ruleEngine.Diagnose(playbackEvent);

            foreach (var diagnosis in diagnoses)
            {
                var diagnosisId = _diagnosisRepository.Insert(playbackEventId, diagnosis);
                _incidentRepository.UpsertOnDiagnosis(diagnosisId, diagnosis.Code, playbackEvent.ItemId, playbackEvent.Client, playbackEvent.DeviceName);
                LogDiagnosis(_logger, diagnosis.Code, diagnosis.Confidence, playbackEvent.SessionId);
            }
        }
#pragma warning disable CA1031
        catch (Exception ex)
        {
            LogPlaybackStoppedHandlerFailed(_logger, ex);
        }
#pragma warning restore CA1031
    }

    private void EvictStaleSnapshots(long now)
    {
        foreach (var entry in _lastKnownPlaybackState)
        {
            if (_timeProvider.GetElapsedTime(entry.Value.CapturedAtTimestamp, now) > SnapshotTtl)
            {
                // Conditional removal: only evict the exact snapshot instance just inspected, so
                // a concurrent PlaybackProgress tick that refreshed this entry between the check
                // above and this call can never have its fresh write evicted out from under it.
                ((ICollection<KeyValuePair<string, PlaybackProgressSnapshot>>)_lastKnownPlaybackState)
                    .Remove(entry);
            }
        }
    }

    [LoggerMessage(Level = LogLevel.Information, Message = "Sentinel diagnosis {Code} ({Confidence}) for session {SessionId}")]
    private static partial void LogDiagnosis(ILogger logger, string code, Confidence confidence, string sessionId);

    [LoggerMessage(Level = LogLevel.Information, Message = "Sentinel playback collector started and subscribed to playback-progress and playback-stopped events")]
    private static partial void LogCollectorStarted(ILogger logger);

    [LoggerMessage(Level = LogLevel.Error, Message = "Sentinel failed to process a playback-stopped event; Jellyfin's own playback handling was not affected")]
    private static partial void LogPlaybackStoppedHandlerFailed(ILogger logger, Exception exception);

    [LoggerMessage(Level = LogLevel.Error, Message = "Sentinel failed to process a playback-progress event; Jellyfin's own playback handling was not affected")]
    private static partial void LogPlaybackProgressHandlerFailed(ILogger logger, Exception exception);
}
