using System;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;
using Jellyfin.Plugin.Sentinel.Diagnostics;
using Jellyfin.Plugin.Sentinel.Domain;
using Jellyfin.Plugin.Sentinel.Persistence;
using MediaBrowser.Controller.Library;
using MediaBrowser.Controller.Session;
using MediaBrowser.Model.Session;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.Sentinel.Collector;

/// <summary>
/// Observes finished playback sessions and turns them into persisted diagnoses.
/// Registered as an <see cref="IHostedService"/> — the main <see cref="Plugin"/> class
/// cannot be one itself, per Jellyfin's plugin constraints.
/// </summary>
/// <remarks>
/// <para>
/// Also subscribes to <c>PlaybackProgress</c>, not just <c>PlaybackStopped</c>. This is required,
/// not optional: verified against <c>Emby.Server.Implementations.Session.SessionManager</c>
/// source, Jellyfin's own <c>OnPlaybackStopped</c> always calls <c>RemoveNowPlayingItem(session)</c>
/// — which resets <c>session.PlayState</c> to a brand-new, empty object and clears
/// <c>session.TranscodingInfo</c> to null — before firing <c>PlaybackStopped</c>. A handler that
/// only listens to <c>PlaybackStopped</c> and reads <c>Session.PlayState</c>/<c>TranscodingInfo</c>
/// will therefore always see empty values, for every session, regardless of whether it actually
/// transcoded. The last known state must be captured earlier, during <c>PlaybackProgress</c>
/// (where it is still live), cached per play session, and consumed when the session stops.
/// </para>
/// <para>
/// The two events are not dispatched the same way — verified against the same source.
/// <c>SessionManager.OnPlaybackProgress</c> invokes its subscribers inline, on whatever thread
/// called it (an incoming client HTTP request, or the session's own once-a-second automatic
/// progress timer). <c>SessionManager.OnPlaybackStopped</c> instead queues its subscribers onto
/// the thread pool via <c>EventHelper.QueueEventIfNotNull</c> and dispatches them asynchronously.
/// Because of that asymmetry, a progress tick already in flight (including one generated by the
/// automatic timer replaying the client's last known state) can still land *after* Jellyfin has
/// cleared <c>TranscodingInfo</c> for a session that is about to stop, but *before* the queued
/// stop handler below consumes the cached snapshot — overwriting good data with empty data. The
/// cache write in <see cref="OnPlaybackProgress"/> below merges rather than replaces for exactly
/// this reason: once real transcode reasons/codecs have been observed for a play session, a
/// later, emptier tick for the same play session never erases them.
/// </para>
/// </remarks>
public sealed partial class PlaybackCollectorHostedService : IHostedService
{
    private static readonly TimeSpan SnapshotTtl = TimeSpan.FromMinutes(30);

    private readonly ISessionManager _sessionManager;
    private readonly RuleEngine _ruleEngine;
    private readonly PlaybackEventRepository _playbackEventRepository;
    private readonly DiagnosisRepository _diagnosisRepository;
    private readonly ILogger<PlaybackCollectorHostedService> _logger;
    private readonly ConcurrentDictionary<string, PlaybackProgressSnapshot> _lastKnownPlaybackState = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="PlaybackCollectorHostedService"/> class.
    /// </summary>
    /// <param name="sessionManager">The Jellyfin session manager to observe playback events from.</param>
    /// <param name="ruleEngine">The rule engine used to diagnose playback events.</param>
    /// <param name="playbackEventRepository">The repository used to persist playback events.</param>
    /// <param name="diagnosisRepository">The repository used to persist diagnoses.</param>
    /// <param name="logger">The logger.</param>
    /// <exception cref="ArgumentNullException">Thrown when any parameter is null.</exception>
    public PlaybackCollectorHostedService(
        ISessionManager sessionManager,
        RuleEngine ruleEngine,
        PlaybackEventRepository playbackEventRepository,
        DiagnosisRepository diagnosisRepository,
        ILogger<PlaybackCollectorHostedService> logger)
    {
        ArgumentNullException.ThrowIfNull(sessionManager);
        ArgumentNullException.ThrowIfNull(ruleEngine);
        ArgumentNullException.ThrowIfNull(playbackEventRepository);
        ArgumentNullException.ThrowIfNull(diagnosisRepository);
        ArgumentNullException.ThrowIfNull(logger);

        _sessionManager = sessionManager;
        _ruleEngine = ruleEngine;
        _playbackEventRepository = playbackEventRepository;
        _diagnosisRepository = diagnosisRepository;
        _logger = logger;
    }

    /// <inheritdoc />
    public Task StartAsync(CancellationToken cancellationToken)
    {
        _sessionManager.PlaybackProgress += OnPlaybackProgress;
        _sessionManager.PlaybackStopped += OnPlaybackStopped;
        LogCollectorStarted(_logger);
        return Task.CompletedTask;
    }

    /// <inheritdoc />
    public Task StopAsync(CancellationToken cancellationToken)
    {
        _sessionManager.PlaybackProgress -= OnPlaybackProgress;
        _sessionManager.PlaybackStopped -= OnPlaybackStopped;

        // Not just tidiness: if this same instance were ever started again (host-lifecycle
        // restart within one process), a stale entry left behind here would otherwise get
        // attributed to whatever unrelated play session next reuses its PlaySessionId slot.
        _lastKnownPlaybackState.Clear();
        return Task.CompletedTask;
    }

    private void OnPlaybackProgress(object? sender, PlaybackProgressEventArgs args)
    {
        // This one genuinely does run inline on Jellyfin's own call path (see class remarks) —
        // an uncaught exception here would propagate into SessionManager.OnPlaybackProgress
        // itself, not just into this plugin. Never let anything escape this handler.
        try
        {
            var playSessionId = args.PlaySessionId;
            if (string.IsNullOrEmpty(playSessionId))
            {
                return;
            }

            var session = args.Session;
            var transcodingInfo = session?.TranscodingInfo;
            var observedReasons = transcodingInfo?.TranscodeReasons;
            var now = DateTime.UtcNow;

            _lastKnownPlaybackState.AddOrUpdate(
                playSessionId,
                _ => new PlaybackProgressSnapshot
                {
                    PlayMethod = session?.PlayState?.PlayMethod,
                    TranscodeReasons = observedReasons ?? default,
                    VideoCodec = transcodingInfo?.VideoCodec,
                    AudioCodec = transcodingInfo?.AudioCodec,
                    CapturedAtUtc = now
                },
                (_, previous) => new PlaybackProgressSnapshot
                {
                    PlayMethod = session?.PlayState?.PlayMethod,
                    TranscodeReasons = observedReasons is { } reasons && reasons != default
                        ? reasons
                        : previous.TranscodeReasons,
                    VideoCodec = transcodingInfo?.VideoCodec ?? previous.VideoCodec,
                    AudioCodec = transcodingInfo?.AudioCodec ?? previous.AudioCodec,
                    CapturedAtUtc = now
                });

            EvictStaleSnapshots(now);
        }
#pragma warning disable CA1031
        catch (Exception ex)
        {
            LogPlaybackProgressHandlerFailed(_logger, ex);
        }
#pragma warning restore CA1031
    }

    private void OnPlaybackStopped(object? sender, PlaybackStopEventArgs args)
    {
        // Unlike OnPlaybackProgress above, Jellyfin dispatches PlaybackStopped asynchronously
        // via EventHelper.QueueEventIfNotNull (its own Task.Run with its own try/catch), so an
        // exception here would not break Jellyfin's own stop handling (which has already run by
        // the time this fires) — but it would still be swallowed by Jellyfin's generic catch
        // instead of logged with this plugin's own session/diagnosis context. Never let anything
        // escape this handler.
        try
        {
            var playSessionId = args.PlaySessionId;
            PlaybackProgressSnapshot? snapshot = null;
            if (!string.IsNullOrEmpty(playSessionId))
            {
                // Removed, not just read: this play session is ending, and leaving it behind
                // would let a stale entry outlive its usefulness (see StopAsync above for why
                // that matters).
                _lastKnownPlaybackState.TryRemove(playSessionId, out snapshot);
            }

            var playbackEvent = PlaybackEventFactory.FromEventArgs(args, snapshot);
            if (playbackEvent is null)
            {
                return;
            }

            var playbackEventId = _playbackEventRepository.Insert(playbackEvent);
            var diagnoses = _ruleEngine.Diagnose(playbackEvent);

            foreach (var diagnosis in diagnoses)
            {
                _diagnosisRepository.Insert(playbackEventId, diagnosis);
                LogDiagnosis(_logger, diagnosis.Code, diagnosis.Confidence, playbackEvent.SessionId);
            }
        }
#pragma warning disable CA1031
        catch (Exception ex)
        {
            LogPlaybackStoppedHandlerFailed(_logger, ex);
        }
#pragma warning restore CA1031
    }

    private void EvictStaleSnapshots(DateTime now)
    {
        foreach (var (playSessionId, snapshot) in _lastKnownPlaybackState)
        {
            if (now - snapshot.CapturedAtUtc > SnapshotTtl)
            {
                _lastKnownPlaybackState.TryRemove(playSessionId, out _);
            }
        }
    }

    [LoggerMessage(Level = LogLevel.Information, Message = "Sentinel diagnosis {Code} ({Confidence}) for session {SessionId}")]
    private static partial void LogDiagnosis(ILogger logger, string code, Confidence confidence, string sessionId);

    [LoggerMessage(Level = LogLevel.Information, Message = "Sentinel playback collector started and subscribed to playback-progress and playback-stopped events")]
    private static partial void LogCollectorStarted(ILogger logger);

    [LoggerMessage(Level = LogLevel.Error, Message = "Sentinel failed to process a playback-stopped event; Jellyfin's own playback handling was not affected")]
    private static partial void LogPlaybackStoppedHandlerFailed(ILogger logger, Exception exception);

    [LoggerMessage(Level = LogLevel.Error, Message = "Sentinel failed to process a playback-progress event; Jellyfin's own playback handling was not affected")]
    private static partial void LogPlaybackProgressHandlerFailed(ILogger logger, Exception exception);
}
